name: ci_util
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.9.0
  pubspec_manager: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
